---
title: "Figure 2 Overview of PTM and Cleavage Patient Frequencies per Disease Group"
author: "Christoph N. Schlaffner"
output:
  pdf_document: default
  html_document: default
---
```{r, include=FALSE}
options(stringsAsFactors = FALSE)
library(ggplot2)
library(R.utils)
library(reshape2)
library(circlize)
library(gridExtra)
library(ggpubr)
library(stringr)

substitueSeparators <- function(x) {
  str_replace_all(str_replace_all(str_replace_all(str_replace_all(x,"@","."),"\\(","."),"\\)","."),"; ","..")
}

substitueSeparators2 <- function(x) {
  str_replace_all(str_replace_all(str_replace_all(str_replace_all(str_replace_all(str_replace_all(x,"@","."),"\\(","."),"\\)","."),"; ",".."),"Non-tryptic","Nontryptic"),"\\-",".")
}

custommean <- function(x) {
  x <- as.numeric(x)
  mean(x)
}

splitPTMs <- function(x) {
  x_split <- unlist(strsplit(x,"_"))
  isoform <- x_split[length(x_split)]
  x <- str_replace_all(x,paste("_",isoform,sep=""),"")
  x <- substitueSeparators(x)
  x_split <- strsplit(x,"\\.")
  y <- unlist(x_split)[nchar(unlist(x_split))>=1|!is.na(as.numeric(unlist(x_split)))]
  idxs <- (which(!is.na(as.numeric(y)))+1)
  
  y <- insert(y,idxs,values=rep(x,length(which(!is.na(as.numeric(y))))))
  extseq <- seq(0,length(idxs)-1,by=1)
  idxs <- idxs + extseq + 1
  insert(y,idxs,values=rep(isoform,length(which(!is.na(as.numeric(y))))))
}

splitCleavages <- function(x) {
  x_split <- unlist(strsplit(x,"_"))
  isoform <- x_split[length(x_split)]
  x <- str_replace_all(x,paste("_",isoform,sep=""),"")
  x <- substitueSeparators2(x)
  x_split <- strsplit(x,"\\.")
  y <- unlist(x_split)[nchar(unlist(x_split))>=1|!is.na(as.numeric(unlist(x_split)))]
  idxs <- (which(!is.na(as.numeric(y)))+1)
  y <- insert(y,idxs[length(idxs)],values=c(x))
  if(length(idxs)==1) {
    y <- insert(y,idxs[length(idxs)],values=y[idxs[length(idxs)]-1])
  }
  c(y,isoform)
}

adjustheights <- function(df_tmp,d,s,direction) {
  idxs1 <- df_tmp$V3
  idxs1_1 <- c(1,idxs1[1:(length(idxs1)-1)])
  
  addition <- c()
  if(length(idxs1)>0) {
    for(i in 1:length(idxs1)) {
      if(i==1) {
        addition <- c(addition,0)
      } else if(i==length(idxs1)) {
        if(addition[length(addition)]!=0) {
          addition <- c(addition,addition[length(addition)]+s)
        } else {
          addition <- c(addition,0)
        }
      } else {
        if(idxs1[i]>idxs1[i-1]+d) {
          addition <- c(addition,0)
        } else {
          addition <- c(addition,addition[length(addition)]+s)
        }
      }
    }
    df_tmp$V4 <- df_tmp$V4+(direction*addition)
  }
  df_tmp
}

adjustheights_all <- function(df_tmp,d,s,nophospho=FALSE) {
  if(nophospho==TRUE) {
    df_tmp2 <- df_tmp
    df_tmp2 <- df_tmp2[order(df_tmp2$V3),]
    df_tmp2 <- adjustheights(df_tmp2,d,s,-1)
    df_tmp <- df_tmp2[order(df_tmp2$V3),]
  } else {
    df_tmp1 <- df_tmp[df_tmp$V1%in%c("Phospho"),]
    df_tmp1 <- df_tmp1[order(df_tmp1$V3),]
    df_tmp2 <- df_tmp[!(df_tmp$V1%in%c("Phospho")),]
    df_tmp2 <- df_tmp2[order(df_tmp2$V3),]
  
    df_tmp1 <- adjustheights(df_tmp1,d,s,1)
    df_tmp2 <- adjustheights(df_tmp2,d,s,-1)
  
    df_tmp <- rbind(df_tmp1,df_tmp2)
    df_tmp <- df_tmp[order(df_tmp$V3),]
  }
  df_tmp
}

readjust_reverse <- function(df_tmp,s,min_v) {
  fliplabel <- rep(1,dim(df_tmp)[1])
  values <- df_tmp$V4 - min_v
  valleys <- which(values==0.0)
  if(length(valleys)>1) {
    peaklengths <- c(valleys[2:length(valleys)],length(values)+1)-valleys
  } else {
    peaklengths <- c(length(values)+1)-valleys
  }
  peaklengths_idxs <- peaklengths>2
  peaklengths <- peaklengths[peaklengths_idxs]
  valleys <- valleys[peaklengths_idxs]
  offset <- ceiling(peaklengths/2)
  run <- peaklengths-ceiling(peaklengths/2)
  if(length(valleys)>0) {
    for(i in 1:length(valleys)) {
      count <- run[i]
      while(count>0) {
        if(count!=run[i] || peaklengths[i]%%2!=0) {
          df_tmp$V4[valleys[i]+offset[i]+(run[i]-count)] <- df_tmp$V4[valleys[i]+offset[i]+(run[i]-count)-1] - s
          fliplabel[valleys[i]+offset[i]+(run[i]-count)] <- -1
        }
        count <- count - 1
      }
    }
  }
  df_tmp$V6 <- fliplabel
  df_tmp
}

readjust_reverse_all <- function(df_tmp,s,min_v,nophospho=FALSE) {
  if(nophospho==TRUE) {
    df_tmp2 <- df_tmp
    df_tmp2 <- df_tmp2[order(df_tmp2$V3),]
    df_tmp2 <- readjust_reverse(df_tmp2,-1*s,-1*min_v)
    df_tmp <- df_tmp2[order(df_tmp2$V3),]
  } else {
    df_tmp1 <- df_tmp[df_tmp$V1%in%c("Phospho"),]
    df_tmp1 <- df_tmp1[order(df_tmp1$V3),]
    df_tmp2 <- df_tmp[!(df_tmp$V1%in%c("Phospho")),]
    df_tmp2 <- df_tmp2[order(df_tmp2$V3),]
  
    df_tmp1 <- readjust_reverse(df_tmp1,s,min_v)
    df_tmp2 <- readjust_reverse(df_tmp2,-1*s,-1*min_v)
  
    df_tmp <- rbind(df_tmp1,df_tmp2)
    df_tmp <- df_tmp[order(df_tmp$V3),]
  }
  df_tmp
}

createFigure <- function(infile,infileC,fileout,min_value,threshold,threshold2) {
  
indata <- read.csv(infile,header=FALSE)
indataC <- read.csv(infileC,header=FALSE)

indata.dup <- indata[2,t(duplicated(t(indata[c(2),])))]
indata.dup <- indata.dup[1,indata.dup[1,]!=""]
indataC.dup <- indataC[2,t(duplicated(t(indataC[c(2),])))]
indataC.dup <- indataC.dup[1,indataC.dup[1,]!=""]

indata[c(1),indata[c(2),]%in%indata.dup[c(1),]] <- "2N4R"
indataC[c(1),indataC[c(2),]%in%indataC.dup] <- "2N4R"

indata <- cbind(indata[,c(1,2)],as.data.frame(t(aggregate(. ~ V1+V2,data=as.data.frame(t(indata[,-c(1,2)])),function(x){y <- as.numeric(x); y <- sum(y); if(y>0) {y<-1} else {y<-0}; y}))))
indataC <- cbind(indataC[,c(1,2)],as.data.frame(t(aggregate(. ~ V1+V2,data=as.data.frame(t(indataC[,-c(1,2)])),function(x){y <- as.numeric(x); y <- mean(y); y}))))

colnames(indata) <- paste("V",1:dim(indata)[2],sep="")
colnames(indataC) <- paste("V",1:dim(indataC)[2],sep="")

columnnames <- colnames(as.matrix(indata[-c(1,2),-c(1,2)]))
columnnamesC <- colnames(as.matrix(indataC[-c(1,2),-c(1,2)]))

indata <- indata[,!((indata[2,]=="")&(indata[1,]!=""))]
indataC <- indataC[,!((indataC[2,]=="")&(indataC[1,]!=""))]

PTMsites <- indata[2,-c(1,2)]
Isosites <- indata[1,-c(1,2)]
PTMsites <- paste(PTMsites,Isosites,sep="_")

Cleavagesites <- indataC[2,-c(1,2)]
Isosites <- indataC[1,-c(1,2)]
Cleavagesites <- paste(Cleavagesites,Isosites,sep="_")


df <- as.data.frame(matrix(unlist(lapply(PTMsites,splitPTMs)),ncol=5,byrow=TRUE))
dfC <- as.data.frame(matrix(unlist(lapply(Cleavagesites,splitCleavages)),ncol=5,byrow=TRUE))

df.full <- df
df <- df[,c(1:3,5)]
df$V6 <- paste(df$V2,df$V3,sep="")
df$V0 <- paste(df$V1,"(",df$V2,")@",df$V3,sep="")
df$V01 <- df$V0
df$V3 <- as.numeric(df$V3)

dfC.full <- dfC
dfC <- dfC[,c(1:3,5)]
dfC$V6 <- paste(dfC$V2,"-",dfC$V3,sep="")
dfC$V0 <- paste(dfC$V1,"@",dfC$V2,"-",dfC$V3,sep="")
dfC$V01 <- dfC$V0
dfC$V2 <- as.numeric(dfC$V2)
dfC$V3 <- as.numeric(dfC$V3)

originalcols <- data.frame(PTM=c("ID","Neuropathology",substitueSeparators(indata[2,-c(1,2)])),iso=c("ID","Neuropathology",substitueSeparators(indata[1,-c(1,2)])),idx=seq(1,dim(indata)[2],by=1))
org <- c(1,2)
maxlength <- dim(df.full)[1]
for(i in 1:maxlength) {
  tmp <- originalcols[which(originalcols$PTM==df.full$V4[i]),]
  tmp <- tmp[tmp$iso==df.full$V5[i],]
  org <- c(org,tmp$idx)
}

originalcols <- data.frame(Cleavage=c("ID","Neuropathology",substitueSeparators2(indataC[2,-c(1,2)])),iso=c("ID","Neuropathology",substitueSeparators2(indataC[1,-c(1,2)])),idx=seq(1,dim(indataC)[2],by=1))
orgC <- c(1,2)
maxlength <- dim(dfC.full)[1]
for(i in 1:maxlength) {
  tmp <- originalcols[which(originalcols$Cleavage==dfC.full$V4[i]),]
  tmp <- tmp[tmp$iso==dfC.full$V5[i],]
  orgC <- c(orgC,tmp$idx)
}

indata2 <- indata[,org]
colnames(indata2) <- c("ID","Neuropathology",df$V01)
indata.tmp <- as.data.frame(cbind(matrix(c("","","","","",""),ncol=2),t(df[,c("V1","V6","V5")])))
colnames(indata.tmp) <- colnames(indata2)
indata2 <- as.data.frame(t(rbind(indata.tmp,indata2)))
indata2.head <- indata2[c(1,2),]
indata2 <- indata2[-c(1,2),]

indataC2 <- indataC[,orgC]
colnames(indataC2) <- c("ID","Neuropathology",dfC$V01)
indataC.tmp <- as.data.frame(cbind(matrix(c("","","","","",""),ncol=2),t(dfC[,c("V1","V6","V5")])))
colnames(indataC.tmp) <- colnames(indataC2)
indataC2 <- as.data.frame(t(rbind(indataC.tmp,indataC2)))
indataC2.head <- indataC2[c(1,2),]
indataC2 <- indataC2[-c(1,2),]

indata2 <- indata2[,-c(3,4,5)]
indata2.head <- indata2.head[,-c(3,4,5)]
indata2 <- aggregate(. ~ V1+V6,data=indata2,max,na.rm=TRUE)
df$V01 <- NULL
df$V5 <- NULL
df <- df[!duplicated(df),]

indataC2 <- indataC2[,-c(3,4,5)]
indataC2.head <- indataC2.head[,-c(3,4,5)]
indataC2 <- aggregate(. ~ V1+V6,data=indataC2,custommean)
dfC$V01 <- NULL
dfC$V5 <- NULL
dfC <- dfC[!duplicated(dfC),]

for(i in 3:dim(indata2)[2]) {
  indata2[,i] <- as.numeric(indata2[,i])
}
filter.ptm <- rowSums(indata2[,-c(1,2)])
indata2 <- indata2[filter.ptm>=threshold,]

for(i in 3:dim(indataC2)[2]) {
  indataC2[,i] <- as.numeric(indataC2[,i])
}
filter.cleav <- rowSums(indataC2[,-c(1,2)])
indataC2 <- indataC2[filter.cleav>=threshold,]

##### filter here!

indata2 <- merge(df,indata2,all=TRUE,by=c("V1","V6"))
indata2 <- indata2[!apply(indata2[,-c(1:5)],1,function(x){all(is.na(x))}),]
indata2$V3.x <- as.numeric(indata2$V3.x)
indata2 <- indata2[order(indata2$V3.x,indata2$V1),]
indata2$V2 <- NULL
indata2$V3.x <- NULL
rownames(indata2) <- indata2$V0
indata2$V0 <- NULL
colnames(indata2) <- colnames(indata2.head)
indata2 <- as.data.frame(t(rbind(indata2.head,indata2)))

indataC2 <- merge(dfC,indataC2,all=TRUE,by=c("V1","V6"))
indataC2 <- indataC2[!apply(indataC2[,-c(1:5)],1,function(x){all(is.na(x))}),]
indataC2$V2 <- as.numeric(indataC2$V2)
indataC2$V3.x <- as.numeric(indataC2$V3.x)
indataC2 <- indataC2[order(indataC2$V2,indataC2$V3.x),]
indataC2$V2 <- NULL
indataC2$V3.x <- NULL
rownames(indataC2) <- indataC2$V0
indataC2$V0 <- NULL
colnames(indataC2) <- colnames(indataC2.head)
indataC2 <- as.data.frame(t(rbind(indataC2.head,indataC2)))

### calculate fequency per disease group
indata2.head <- indata2[c(1,2),]
indata2.head$ID <- NULL
indata2 <- indata2[-c(1,2),]
rownames(indata2) <- indata2$ID
indata2$ID <- NULL
indata2[,-1] <- apply(indata2[,-1],2,function(x){as.numeric(x)})
indata2 <- aggregate(.~Neuropathology,data=indata2,mean)
indata2 <- as.data.frame(t(rbind(indata2.head,indata2)))
indata2 <- merge(df,indata2,all=TRUE)
colnames(indata2) <- c("modification","site","AA","seg.po",indata2[1,5:13])
indata2 <- indata2[-1,]

indataC2.head <- indataC2[c(1,2),]
indataC2.head$ID <- NULL
indataC2 <- indataC2[-c(1,2),]
rownames(indataC2) <- indataC2$ID
indataC2$ID <- NULL
indataC2[,-1] <- apply(indataC2[,-1],2,function(x){as.numeric(x)})
indataC2 <- aggregate(.~Neuropathology,data=indataC2,mean)
indataC2 <- as.data.frame(t(rbind(indataC2.head,indataC2)))
indataC2 <- merge(dfC,indataC2,all=TRUE)
colnames(indataC2) <- c("modification","site","seg.po","seg.po.2",indataC2[1,5:13])
indataC2 <- indataC2[-1,]

indata2$AD <- as.numeric(indata2$AD)
indata2$CBD <- as.numeric(indata2$CBD)
indata2$CTRL <- as.numeric(indata2$CTRL)
indata2$PiD <- as.numeric(indata2$PiD)
indata2$PSP <- as.numeric(indata2$PSP)
indata2$DLB <- as.numeric(indata2$DLB)
indata2$CTE <- as.numeric(indata2$CTE)
indata2$fAD <- as.numeric(indata2$fAD)

indataC2$AD <- as.numeric(indataC2$AD)
indataC2$CBD <- as.numeric(indataC2$CBD)
indataC2$CTRL <- as.numeric(indataC2$CTRL)
indataC2$PiD <- as.numeric(indataC2$PiD)
indataC2$PSP <- as.numeric(indataC2$PSP)
indataC2$DLB <- as.numeric(indataC2$DLB)
indataC2$CTE <- as.numeric(indataC2$CTE)
indataC2$fAD <- as.numeric(indataC2$fAD)

indata2 <- indata2[,-c(5)]
indataC2 <- indataC2[,-c(5)]

colnames(indata2) <- c("modification","site","AA","seg.po","AD","CBD","CTE","CTR","DLB","fAD","PiD","PSP")
colnames(indataC2) <- c("modification","site","seg.po","seg.po.2","AD","CBD","CTE","CTR","DLB","fAD","PiD","PSP")


indata2 <- indata2[apply(indata2[,c(5:12)],1,sum)>0.0,]
indata2$seg.po <- as.numeric(indata2$seg.po)

indataC2 <- indataC2[apply(indataC2[,c(5:12)],1,sum)>0.0,]
indataC2$seg.po <- as.numeric(indataC2$seg.po)
indataC2$seg.po.2 <- as.numeric(indataC2$seg.po.2)

seg.f <- data.frame(seg.name=c("N-term","N1","N2","Mid","PRR","R1","R2","R3","R4","C-term"),seg.Start=c(1,45,74,103,151,242,273,304,335,372),seg.End=c(44,73,102,150,241,272,303,334,371,441),the.v=c(NA),NO=c(NA))
seg.name <- c("N-term","N1","N2","Mid","PRR","R1","R2","R3","R4","C-term")
indata2$seg.name <- lapply(indata2$seg.po,function(x,mapping){ mapping$seg.name[which(x>= mapping$seg.Start)[which(x>=mapping$seg.Start)%in%which(x<=mapping$seg.End)]] },seg.f)
indata2 <- indata2[,c("seg.name","AA","seg.po","CTR","DLB","PSP","PiD","CBD","CTE","AD","fAD","modification","site")]

seg.f$seg.Start <- as.character(seg.f$seg.Start)
seg.f$seg.End <- as.character(seg.f$seg.End)
seg.annotation <- indata2[,c(1,2,12,13)]

segC.f <- data.frame(seg.name=c("N-term","N1","N2","Mid","PRR","R1","R2","R3","R4","C-term"),seg.Start=c(1,45,74,103,151,242,273,304,335,372),seg.End=c(44,73,102,150,241,272,303,334,371,441),the.v=c(NA),NO=c(NA))
segC.name <- c("N-term","N1","N2","Mid","PRR","R1","R2","R3","R4","C-term")
indataC2$seg.name <- lapply(indataC2$seg.po,function(x,mapping){ mapping$seg.name[which(x>= mapping$seg.Start)[which(x>=mapping$seg.Start)%in%which(x<=mapping$seg.End)]] },segC.f)
indataC2$seq.name.2 <- lapply(indataC2$seg.po.2,function(x,mapping){ mapping$seg.name[which(x>= mapping$seg.Start)[which(x>=mapping$seg.Start)%in%which(x<=mapping$seg.End)]] },segC.f)
indataC2 <- indataC2[,c("seg.name","seg.po","seg.po.2","CTR","DLB","PSP","PiD","CBD","CTE","AD","fAD","modification","site")]
segC.f$seg.Start <- as.character(segC.f$seg.Start)
segC.f$seg.End <- as.character(segC.f$seg.End)
segC.annotation <- indataC2[,c(1,2,3,12,13)]

df <- indata2[,c("modification","AA","seg.po","site")]
colnames(df) <- c("V1","V2","V3","V5")
df <- df[order(df$V3),]
df <- df[!duplicated(df),]
df <- df[df$V1!="Oxidation",]
df <- df[df$V1!="Deamidated",]
df <- df[!(df$V1=="GG"&df$V2=="S"),]

dfC <- indataC2[,c("modification","seg.po","seg.po.2","site")]
colnames(dfC) <- c("V1","V2","V3","V5")
dfC <- dfC[order(dfC$V3),]
dfC <- dfC[!duplicated(dfC),]

minval <- 0.13
df$V4 <- rep(minval,dim(df)[1])
df[!(df$V1%in%c("Phospho")),]$V4 <- -1*minval
df$V3 <- as.numeric(df$V3)
df <- df[!(df$V1%in%c("Oxidation")),]
df <- df[!(df$V1%in%c("Deamidated")),]

dfC$V4 <- rep(minval,dim(dfC)[1])
dfC$V3 <- as.numeric(dfC$V3)

df <- adjustheights_all(df,22,0.1,nophospho=TRUE)
df <- readjust_reverse_all(df,0.1,minval,nophospho=TRUE)

dfC <- adjustheights_all(dfC,22,0.1,nophospho=TRUE)
dfC <- readjust_reverse_all(dfC,0.1,minval,nophospho=TRUE)

df2 <- data.frame(x1=c(1,45,74,103,151,242,273,304,335,372),x2=c(45,74,103,151,242,273,304,335,372,441),y1=rep(-0.08,10),y2=rep(0.08,10),colo=c("A","B","B","A","B","B","B","B","B","A"),name=c("","N1","N2","Mid","Proline-rich region","R1","R2","R3","R4",""))
dfC2 <- data.frame(x1=c(1,45,74,103,151,242,273,304,335,372),x2=c(45,74,103,151,242,273,304,335,372,441),y1=rep(-0.08,10),y2=rep(0.08,10),colo=c("A","B","B","A","B","B","B","B","B","A"),name=c("","N1","N2","Mid","Proline-rich region","R1","R2","R3","R4",""))

textsize <- 5
ratio <- 4/5
align <- 0.18

indata2 <- indata2[!(indata2$modification=="GG"&indata2$AA=="S"),]
seg <- data.frame(sectors=c("N-term","N1","N2","Mid","PRR","R1","R2","R3","R4","C-term"),x=c(1,45,74,103,151,242,273,304,335,372),y=c(44,73,102,150,241,272,303,334,371,441),the.v=c(NA),NO=c(NA))
df <- data.frame(sectors=character(),x=numeric(),y=numeric())
for(i in 1:dim(seg)[1]) {
  df.tmp <- data.frame(sectors=rep(seg$sectors[i],length(seg$x[i]:seg$y[i])),x=c(seg$x[i]:seg$y[i]),y=c(seg$x[i]:seg$y[i]))
  df <- rbind(df,df.tmp)
}
df$sectors <- factor(df$sectors,levels=seg$sectors)
indata2.tmp <- indata2
colnames(indata2.tmp) <- c("sectors","AA","x","CTR","DLB","PSP","PiD","CBD","CTE","AD","fAD","modification","site")
df2 <- merge(df,indata2.tmp,all=TRUE)
df2[is.na(df2$AD),]$AD <- 0
df2[is.na(df2$CBD),]$CBD <- 0
df2[is.na(df2$CTR),]$CTR <- 0
df2[is.na(df2$CTE),]$CTE <- 0
df2[is.na(df2$DLB),]$DLB <- 0
df2[is.na(df2$PiD),]$PiD <- 0
df2[is.na(df2$PSP),]$PSP <- 0
df2[is.na(df2$fAD),]$fAD <- 0
df2$AD <- as.numeric(df2$AD)
df2$CBD <- as.numeric(df2$CBD)
df2$CTR <- as.numeric(df2$CTR)
df2$PiD <- as.numeric(df2$PiD)
df2$PSP <- as.numeric(df2$PSP)
df2$DLB <- as.numeric(df2$DLB)
df2$CTE <- as.numeric(df2$CTE)
df2$fAD <- as.numeric(df2$fAD)

df2$AA <- NULL
df3 <- df2[!is.na(df2$site),]
df3.t <- df3
if(min_value>0.00) {
  df3.t[df3.t$AD<min_value,]$AD <- 0.0
  df3.t[df3.t$CBD<min_value,]$CBD <- 0.0
  df3.t[df3.t$CTR<min_value,]$CTR <- 0.0
  df3.t[df3.t$PiD<min_value,]$PiD <- 0.0
  df3.t[df3.t$PSP<min_value,]$PSP <- 0.0
  df3.t[df3.t$DLB<min_value,]$DLB <- 0.0
  df3.t[df3.t$CTE<min_value,]$CTE <- 0.0
  df3.t[df3.t$fAD<min_value,]$fAD <- 0.0
}

segC <- data.frame(sectors=c("N-term","N1","N2","Mid","PRR","R1","R2","R3","R4","C-term"),x=c(1,45,74,103,151,242,273,304,335,372),y=c(44,73,102,150,241,272,303,334,371,441),the.v=c(NA),NO=c(NA))
dfC <- data.frame(sectors=character(),x=numeric(),y=numeric())
for(i in 1:dim(segC)[1]) {
  dfC.tmp <- data.frame(sectors=rep(segC$sectors[i],length(segC$x[i]:segC$y[i])),x=c(segC$x[i]:segC$y[i]),y=c(segC$x[i]:segC$y[i]))
  dfC <- rbind(dfC,dfC.tmp)
}
dfC$sectors <- factor(dfC$sectors,levels=segC$sectors)
indataC2.tmp <- indataC2
colnames(indataC2.tmp) <- c("sectors","x","x.2","CTR","DLB","PSP","PiD","CBD","CTE","AD","fAD","modification","site")
dfC2 <- merge(dfC,indataC2.tmp,all=TRUE)
dfC2[is.na(dfC2$AD),]$AD <- 0
dfC2[is.na(dfC2$CBD),]$CBD <- 0
dfC2[is.na(dfC2$CTR),]$CTR <- 0
dfC2[is.na(dfC2$CTE),]$CTE <- 0
dfC2[is.na(dfC2$DLB),]$DLB <- 0
dfC2[is.na(dfC2$PiD),]$PiD <- 0
dfC2[is.na(dfC2$PSP),]$PSP <- 0
dfC2[is.na(dfC2$fAD),]$fAD <- 0
dfC2$AD <- as.numeric(dfC2$AD)
dfC2$CBD <- as.numeric(dfC2$CBD)
dfC2$CTR <- as.numeric(dfC2$CTR)
dfC2$PiD <- as.numeric(dfC2$PiD)
dfC2$PSP <- as.numeric(dfC2$PSP)
dfC2$DLB <- as.numeric(dfC2$DLB)
dfC2$CTE <- as.numeric(dfC2$CTE)
dfC2$fAD <- as.numeric(dfC2$fAD)
dfC3 <- dfC2[!is.na(dfC2$site),]
dfC3.t <- dfC3
if(min_value>0.00) {
  dfC3.t[dfC3.t$AD<min_value,]$AD <- 0.0
  dfC3.t[dfC3.t$CBD<min_value,]$CBD <- 0.0
  dfC3.t[dfC3.t$CTR<min_value,]$CTR <- 0.0
  dfC3.t[dfC3.t$PiD<min_value,]$PiD <- 0.0
  dfC3.t[dfC3.t$PSP<min_value,]$PSP <- 0.0
  dfC3.t[dfC3.t$DLB<min_value,]$DLB <- 0.0
  dfC3.t[dfC3.t$CTE<min_value,]$CTE <- 0.0
  dfC3.t[dfC3.t$fAD<min_value,]$fAD <- 0.0
}

df3 <- df3[apply(df3.t[,c(4:11)],1,sum)>0.0,]

bed <- df3[,c("sectors","x","y","modification","site")]
colnames(bed) <- c("chr","start","end","modification","site")
bed <- bed[!is.na(bed$site),]
bed <- bed[bed$modification%in%c("Acetyl","Citrullination","Methyl","Phospho","GG"),]

dfC3 <- dfC3[apply(dfC3.t[,c(5:12)],1,sum)>0.0,]
dfC3$y <- dfC3$x.2
dfC3$x.2 <- NULL

bedC <- dfC3[,c("sectors","x","y","modification","site")]
colnames(bedC) <- c("chr","start","end","modification","site")
bedC <- bedC[!is.na(bedC$site),]
bedC <- bedC[bedC$modification%in%c("Non-tryptic"),]

col = c("Acetyl"="#93478F","Citrullination"="#FF17E3","Methyl"="#FF7369","Phospho"="#000000","GG"="#7AB77C")
bgcol <- c("AD"="#E41A1C","CTR"="#4DAF4A","PiD"="#984EA3","PSP"="#FF7F00","CBD"="#FFD92F","DLB"="#8DD3C7","CTE"="#1740B6","fAD"="#9C0B0C","CAA"="#914B00","NPCAD"="#FF17E3","FTLD"="#17DFFF")

alpha <- 0.1
selectbordercolor <- function(x) {
  "#000000"
}
fact <- c(1.2,1.2,1.2,1.2,1.2)
fact2 <- c(1,1.5,2,2.5,3)

thicktracks <- 0.06
thintracks <- 0.01
m1 <- 0.0025
m2 <- 0.005
lwd <- 0.5
lwd2 <- 2
lwd3 <- 1
lty1 <- 1
lty2 <- 1
text_x <- 10
text_y <- 0.5
facing <- "clockwise"
labelsize <- 0.6

major_at <- c(1,45,74,103,151,242,273,304,335,372,441)
major_at <- c(1,50,100,150,200,250,300,350,400,441)

sharedPTM <- function(x) {
  logcutoff <- 1
  percentcutoffupper <- 0.1
  percentcutofflower <- 0.05
  overUpper <- sum(x>=percentcutoffupper)
  overLower <- sum(x>=percentcutofflower)
  overLowerunderUpper <- overUpper-overLower
  result <- "unique"
  if(overUpper>1) {
    result <- "shared"
  }
  if(overUpper==1 && overLowerunderUpper>1) {
    y <- log(max(x)/x)
    y[y==Inf] <- 0
    underthresholdover0 <- sum(y<logcutoff) - sum(y==0)
    if(underthresholdover0>=1) {
      result <- "shared"
    }
  }
  if(overUpper==0&&overLower>1) {
    y <- log(max(x)/x)
    y[y==Inf] <- 0
    underthresholdover0 <- sum(y<logcutoff) - sum(y==0)
    if(underthresholdover0>=1) {
      result <- "shared"
    }
  }
  result
}

df4 <- df3
df4$y <- NULL
df4$shared <- apply(df4[,c(3:10)],1,sharedPTM)
df4.melt <- melt(df4,id.vars=c("sectors","x","modification","site","shared"))
df4.melt <- df4.melt[(df4.melt$modification!="Oxidation"),]
df4.melt <- df4.melt[(df4.melt$modification!="Deamidated"),]
df4.melt$variable <- as.character(df4.melt$variable)

dfC4 <- dfC3
dfC4$shared <- apply(dfC4[,c(4:11)],1,sharedPTM)
dfC4.melt <- melt(dfC4,id.vars=c("sectors","x","y","modification","site","shared"))
dfC4.melt$variable <- as.character(dfC4.melt$variable)

df4.melt.unique <- df4.melt[df4.melt$shared=="unique",]
df4.melt.unique$shared <- NULL
df4.melt.shared <- df4.melt[df4.melt$shared=="shared",]
df4.melt.shared$shared <- NULL
df4.melt.shared$variable <- NULL
cnames <- colnames(df4.melt.shared)
df4.melt.shared <- aggregate(df4.melt.shared$value,by=list(df4.melt.shared$sectors,df4.melt.shared$x,df4.melt.shared$modification,df4.melt.shared$site),mean)
colnames(df4.melt.shared) <- cnames

dfC4.melt.unique <- dfC4.melt[dfC4.melt$shared=="unique",]
dfC4.melt.unique$shared <- NULL
dfC4.melt.shared <- dfC4.melt[dfC4.melt$shared=="shared",]
dfC4.melt.shared$shared <- NULL
dfC4.melt.shared$variable <- NULL
cnamesC <- colnames(dfC4.melt.shared)
dfC4.melt.shared <- aggregate(dfC4.melt.shared$value,by=list(dfC4.melt.shared$sectors,dfC4.melt.shared$x,dfC4.melt.shared$y,dfC4.melt.shared$modification,dfC4.melt.shared$site),mean)
colnames(dfC4.melt.shared) <- cnamesC

df5 <- df4[,c("modification","x","site")]
colnames(df5) <- c("V1","V3","V5")
df5 <- df5[!duplicated(df5),]
df5 <- df5[order(df5$V3,df5$V1),]
df5 <- df5[df5$V1!="Oxidation",]
df5 <- df5[df5$V1!="Deamidated",]

dfC5 <- dfC4[,c("modification","x","y","site")]
colnames(dfC5) <- c("V1","V3","V33","V5")
dfC5 <- dfC5[!duplicated(dfC5),]
dfC5 <- dfC5[order(dfC5$V3,dfC5$V33,dfC5$V1),]


minval <- 0.13
df5$V4 <- rep(minval,dim(df5)[1])
df5$V4 <- -1*minval
df5$V3 <- as.numeric(df5$V3)
df5$V1 <- NULL
df5 <- df5[!duplicated(df5),]
df5$V1 <- rep("Phospho",dim(df5)[1])
df5 <- adjustheights_all(df5,14,0.1,TRUE)
df5 <- readjust_reverse_all(df5,0.1,minval,TRUE)
df5$V6[dim(df5)[1]] <- 1
df5$V7 <- seq(1,dim(df5)[1],by=1)

dfC5$V4 <- rep(minval,dim(dfC5)[1])
dfC5$V4 <- -1*minval
dfC5$V3 <- as.numeric(dfC5$V3)
dfC5$V33 <- as.numeric(dfC5$V33)
dfC5$V1 <- NULL
dfC5 <- dfC5[!duplicated(dfC5),]
dfC5$V1 <- rep("Phospho",dim(dfC5)[1])
dfC5 <- adjustheights_all(dfC5,14,0.1,TRUE)
dfC5 <- readjust_reverse_all(dfC5,0.1,minval,TRUE)
dfC5$V6[dim(dfC5)[1]] <- 1
dfC5$V7 <- seq(1,dim(dfC5)[1],by=1)


df6 <- data.frame(x1=c(1,45,74,103,151,242,273,304,335,372),x2=c(45,74,103,151,242,273,304,335,372,441),y1=rep(-0.1,10),y2=rep(0.1,10),colo=c("A","B","B","A","B","B","B","B","B","A"),name=c("","N1","N2","Mid","Proline-rich region","R1","R2","R3","R4",""),sectors=c("N-term","N1","N2","Mid","PRR","R1","R2","R3","R4","C-term"))


df4.tmp <- df4.melt[,c("x","modification","site","sectors")]
df4.tmp <- df4.tmp[!duplicated(df4.tmp),]
df4.tmp <- df4.tmp[order(df4.tmp$x),]
df4.tmp$rank <- seq(1,dim(df4.tmp)[1],by=1)
df4.melt <- merge(df4.melt,df4.tmp,all=TRUE)

dfC4.tmp <- dfC4.melt[,c("x","y","modification","site","sectors")]
dfC4.tmp <- dfC4.tmp[!duplicated(dfC4.tmp),]
dfC4.tmp <- dfC4.tmp[order(dfC4.tmp$x,dfC4.tmp$y),]
dfC4.tmp$rank <- seq(1,dim(dfC4.tmp)[1],by=1)
dfC4.melt <- merge(dfC4.melt,dfC4.tmp,all=TRUE)

df4.melt2 <- df4.melt
df4.melt2$shared <- rep("shared",dim(df4.melt2)[1])
df4.melt2$variable <- rep("Modification",dim(df4.melt2)[1])
df4.melt2$value <- rep(1,dim(df4.melt2)[1])
df4.melt2 <- df4.melt2[!duplicated(df4.melt2),]

dfC4.melt2 <- dfC4.melt
dfC4.melt2$shared <- rep("shared",dim(dfC4.melt2)[1])
dfC4.melt2$variable <- rep("Modification",dim(dfC4.melt2)[1])
dfC4.melt2$value <- rep(1,dim(dfC4.melt2)[1])
dfC4.melt2 <- dfC4.melt2[!duplicated(dfC4.melt2),]

df4.melt <- rbind(df4.melt,df4.melt2)
dfC4.melt <- rbind(dfC4.melt,dfC4.melt2)

textsize <- 4
ratio <- 4/5
align <- 0.18


alpha <- 1
selectbackgroundcolor <- function(x) {
  scales::alpha(bgcol[x],alpha=alpha)
}
indent <- 1.5
df5$V4 <- abs(df5$V4)
dfC5$V4 <- abs(dfC5$V4)


g_legend<-function(a.gplot){
  tmp <- ggplot_gtable(ggplot_build(a.gplot))
  leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
  legend <- tmp$grobs[[leg]]
  return(legend)}


df4.melt2 <- df4.melt[df4.melt$variable=="Modification",]
df4.melt2$cleavage <- sample(c("C-term","N-term"),dim(df4.melt2)[1],replace=TRUE)
df4.melt <- df4.melt[df4.melt$variable!="Modification",]
variable.labs <- c("CTR","DLB","PSP","PiD","CBD","CTE","AD","fAD")
names(variable.labs) <- c("CTR","DLB","PSP","PiD","CBD","CTE","AD","fAD")
df4.melt$variable <- factor(df4.melt$variable,levels=c("CTR","DLB","PSP","PiD","CBD","CTE","AD","fAD"))

dfC4.melt2 <- dfC4.melt[dfC4.melt$variable=="Modification",]
dfC4.melt2$cleavage <- sample(c("C-term","N-term"),dim(dfC4.melt2)[1],replace=TRUE)
dfC4.melt <- dfC4.melt[dfC4.melt$variable!="Modification",]
variable.labsC <- c("CTR","DLB","PSP","PiD","CBD","CTE","AD","fAD")
names(variable.labsC) <- c("CTR","DLB","PSP","PiD","CBD","CTE","AD","fAD")
dfC4.melt$variable <- factor(dfC4.melt$variable,levels=c("CTR","DLB","PSP","PiD","CBD","CTE","AD","fAD"))

cleavage_col <- c("N-term"="#607196","C-term"="#A6608B")


textsize <- 12

df5$V4 <- abs(df5$V4)
dfC5$V4 <- abs(dfC5$V4)

####### extract 1
df6.tmp <- df6[df6$sectors%in%df4.melt$sectors,]
changingdf <- df6.tmp[order(df6.tmp$x2,decreasing=TRUE),]
changingdf <- changingdf[,c("x2","sectors")]
if(changingdf$x2[1]==441) {
  changingdf <- changingdf[-1,]
}

df4.melt.tmp <- df4.melt
splitrank <- c()
for(tempidx in changingdf$x2) {
  splitrank <- c(min(df4.melt[df4.melt$x>=tempidx,]$rank),splitrank+1)
  df4.melt[df4.melt$x>=tempidx,]$rank <- df4.melt[df4.melt$x>=tempidx,]$rank + 1
}
df6.tmp <- df6[df6$sectors%in%df4.melt$sectors,]
changingdf <- df6.tmp[order(df6.tmp$x2,decreasing=FALSE),]
changingdf <- changingdf[,c("x2","sectors")]
changingdf$x <- (c(splitrank,max(df4.melt$rank)) + c(0,splitrank)) / 2 

##### extract 2
df6.tmp <- df6[df6$sectors%in%df4.melt2$sectors,]
changingx <- df6.tmp$x2[order(df6.tmp$x2,decreasing=TRUE)]
if(changingx[1]==441) {
  changingx <- changingx[-1]
}

df4.melt2.tmp <- df4.melt2
splitrank2 <- c()
for(tempidx in changingx) {
  splitrank2 <- c(min(df4.melt2[df4.melt2$x>=tempidx,]$rank),splitrank2+1)
  df4.melt2[df4.melt2$x>=tempidx,]$rank <- df4.melt2[df4.melt2$x>=tempidx,]$rank + 1
  
}

##### extract 3
df6.tmp <- df6[df6$sectors%in%dfC4.melt$sectors,]
changingdfC <- df6.tmp[order(df6.tmp$x2,decreasing=TRUE),]
changingdfC <- changingdfC[,c("x2","sectors")]
if(changingdfC$x2[1]==441) {
  changingdfC <- changingdfC[-1,]
}

dfC4.melt.tmp <- dfC4.melt
splitrankC <- c()
for(tempidx in changingdfC$x2) {
  splitrankC <- c(min(dfC4.melt[dfC4.melt$x>=tempidx,]$rank),splitrankC+1)
  dfC4.melt[dfC4.melt$x>=tempidx,]$rank <- dfC4.melt[dfC4.melt$x>=tempidx,]$rank + 1
  
}
df6.tmp <- df6[df6$sectors%in%dfC4.melt$sectors,]
changingdfC <- df6.tmp[order(df6.tmp$x2,decreasing=FALSE),]
changingdfC <- changingdfC[,c("x2","sectors")]
changingdfC$x <- (c(splitrankC,max(dfC4.melt$rank)) + c(0,splitrankC)) / 2 

##### extract 4
df6.tmp <- df6[df6$sectors%in%dfC4.melt2$sectors,]
changingx <- df6.tmp$x2[order(df6.tmp$x2,decreasing=TRUE)]
if(changingx[1]==441) {
  changingx <- changingx[-1]
}

dfC4.melt2.tmp <- dfC4.melt2
splitrankC2 <- c()
for(tempidx in changingx) {
  splitrankC2 <- c(min(dfC4.melt2[dfC4.melt2$x>=tempidx,]$rank),splitrankC2+1)
  dfC4.melt2[dfC4.melt2$x>=tempidx,]$rank <- dfC4.melt2[dfC4.melt2$x>=tempidx,]$rank + 1
  
}


df4.melt <- df4.melt[order(df4.melt$rank),]

linedist <- 0
topmargin <- 0.9
bottommargin <- -2.5
gridlwd <- 0.5
gridlcol <- "black"

p <- ggplot() + 
  geom_tile(data=subset(df4.melt,modification=="Phospho"),aes(y=-rank,x=variable,fill=value),colour=gridlcol,height=1,lwd=gridlwd) +
  scale_fill_gradient2("PTM Patient Frequency", limits=c(0, 1), midpoint = 0.5, low="#B35806", mid="#F5F5F5", high="#01665E", breaks=c(0.0,0.5,1.0), labels=c("0 %","50 %","100 %")) +
  geom_tile(data=subset(df4.melt,modification=="GG"),aes(y=-rank,x=variable,fill=value),colour=gridlcol,height=1,lwd=gridlwd) +
  geom_tile(data=subset(df4.melt,modification=="Acetyl"),aes(y=-rank,x=variable,fill=value),colour=gridlcol,height=1,lwd=gridlwd) +
  geom_tile(data=subset(df4.melt,modification=="Methyl"),aes(y=-rank,x=variable,fill=value),colour=gridlcol,height=1,lwd=gridlwd) +
  geom_tile(data=subset(df4.melt,modification=="Citrullination"),aes(y=-rank,x=variable,fill=value),colour=gridlcol,height=1,lwd=gridlwd) +
  geom_hline(yintercept=-splitrank,colour="gray24",lwd=1.5) +
  scale_x_discrete(expand=c(0,0)) + 
  scale_y_continuous(expand=c(0,0),limits=c(-(max(df4.melt$rank)+0.7),0),breaks=-changingdf$x,labels=changingdf$sectors,position="left") + 
  theme(legend.position="bottom",strip.text.x=element_text(size=textsize,angle=90),legend.title=element_text(size=textsize),legend.text=element_text(size=textsize),panel.grid=element_blank(),plot.margin=unit(c(0.1,0.1,bottommargin,0.5),"line"),panel.background=element_blank(),axis.text.y=element_text(size=textsize),axis.text.x=element_blank(),axis.ticks=element_blank(),axis.title=element_blank(),panel.spacing.x=unit(0,"lines")) +
  facet_wrap(~variable,scales="free_x",ncol=11,strip.position="top",labeller=labeller(variable=variable.labs)) +
  labs(fill="PTM Patient Frequency") +
  guides(fill=guide_colorbar(title.position="top",barwidth=unit(40,"mm")))

df4.melt2 <- df4.melt2[order(df4.melt2$rank),]

p2 <- ggplot() + 
  geom_tile(data=subset(df4.melt2,variable=="Modification"),aes(y=-rank,x=variable,fill=modification),colour=gridlcol,height=1,lwd=gridlwd) +
  scale_fill_manual("PTM", values=col, labels=c("Acetyl"="Acetylation","Citrullination"="Citrullination","Methyl"="Methylation","Phospho"="Phosphorylation","GG"="Ubiquitination")) +
  scale_x_discrete(expand=c(0,0)) + 
  scale_y_continuous(expand=c(0,-0.3),limits=c(-(max(df4.melt2$rank)+1),0)) + 
  theme(legend.position="bottom",legend.title=element_text(size=textsize),legend.text=element_text(size=textsize),panel.grid=element_blank(),plot.margin=unit(c(topmargin-0.2,0.1,bottommargin,0.1),"line"),panel.background=element_blank(),axis.text=element_blank(),axis.ticks=element_blank(),axis.title=element_blank(),panel.spacing.y=unit(linedist,"lines")) +
  guides(fill=guide_legend(ncol=3,title.position="top"))

p3 <- ggplot() + 
  geom_tile(data=subset(dfC4.melt,modification=="Nontryptic"),aes(y=-rank,x=variable,fill=value),colour=gridlcol,height=1,lwd=gridlwd) +
  scale_fill_gradient2("Proteolytic Cleavage Patient Frequency", limits=c(0, 1), midpoint = 0.5, low="#B35806", mid="#F7F7F7", high="#542788", breaks=c(0.0,0.5,1.0), labels=c("0 %","50 %","100 %")) +
  geom_hline(yintercept=-splitrankC,colour="gray24",lwd=1.5) +
  scale_x_discrete(expand=c(0,0)) + 
  scale_y_continuous(expand=c(0,0),limits=c(-(max(dfC4.melt$rank)+1),0),breaks=-changingdfC$x,labels=changingdfC$sectors,position="right") + 
  theme(legend.position="bottom",strip.text.x=element_text(size=textsize,angle=90),legend.title=element_text(size=textsize),legend.text=element_text(size=textsize),panel.grid=element_blank(),plot.margin=unit(c(0.1,0.5,bottommargin,0.1),"line"),panel.background=element_blank(),axis.text.y=element_text(size=textsize),axis.text.x=element_blank(),axis.ticks=element_blank(),axis.title=element_blank(),panel.spacing.x=unit(0,"lines")) +
  facet_wrap(~variable,scales="free_x",ncol=11,strip.position="top",labeller=labeller(variable=variable.labs)) +
  labs(fill="Proteolytic Cleavage Patient Frequency") +
  guides(fill=guide_colorbar(title.position="top",barwidth=unit(40,"mm")))

p4 <- ggplot() + 
  geom_tile(data=subset(dfC4.melt2,variable=="Modification"),aes(y=-rank,x=variable,fill=modification),colour=gridlcol,height=1,lwd=gridlwd) +
  scale_fill_manual("Peptide Cleavage", values=cleavage_col) +
  scale_x_discrete(expand=c(0,0)) + 
  scale_y_continuous(expand=c(0,0),limits=c(-(max(dfC4.melt$rank)+1),0)) + 
  theme(legend.position="bottom",legend.title=element_text(size=textsize),legend.text=element_text(size=textsize),panel.grid=element_blank(),plot.margin=unit(c(topmargin,0.1,bottommargin,0.1),"line"),panel.background=element_blank(),axis.text=element_blank(),axis.ticks=element_blank(),axis.title=element_blank(),panel.spacing.y=unit(linedist,"lines")) +
  labs(fill="Peptide Cleavage") +
  guides(fill=guide_legend(ncol=2,title.position="top"))


p_legend<-g_legend(p)
p <- p + theme(legend.position="none")
p2_legend<-g_legend(p2)
p2 <- p2 + theme(legend.position="none")
p3_legend<-g_legend(p3)
p3 <- p3 + theme(legend.position="none")

p4 <- p4 + theme(legend.position="none")

g <- ggplot_gtable(ggplot_build(p))
stripl <- which(grepl('strip-t', g$layout$name))
fills <- bgcol
fills <- bgcol[c(2,6,4,3,5,7,1,8)]
textcols <- c("#000000","#000000","#000000","#E6E6E6","#000000","#E6E6E6","#000000","#E6E6E6")

k <- 1
for (i in stripl) {
  j <- which(grepl('background', g$grobs[[i]]$grobs[[1]]$childrenOrder))
  g$grobs[[i]]$grobs[[1]]$children[[j]]$gp$fill <- fills[k]
  j <- which(grepl('text', g$grobs[[i]]$grobs[[1]]$childrenOrder))
  g$grobs[[i]]$grobs[[1]]$children[[j]]$children[[1]]$gp$col <- textcols[k]
  k <- k+1
}
scalingfactor <- 1

g2 <- ggplot_gtable(ggplot_build(p3))
stripl <- which(grepl('strip-t', g2$layout$name))
fills <- bgcol
fills <- bgcol[c(2,6,4,3,5,7,1,8)]
textcols <- c("#000000","#000000","#000000","#E6E6E6","#000000","#E6E6E6","#000000","#E6E6E6")

k <- 1
for (i in stripl) {
  j <- which(grepl('background', g2$grobs[[i]]$grobs[[1]]$childrenOrder))
  g2$grobs[[i]]$grobs[[1]]$children[[j]]$gp$fill <- fills[k]
  j <- which(grepl('text', g2$grobs[[i]]$grobs[[1]]$childrenOrder))
  g2$grobs[[i]]$grobs[[1]]$children[[j]]$children[[1]]$gp$col <- textcols[k]
  k <- k+1
}
scalingfactor <- 1

miny <- -0.1
maxy <- 0.1
df7 <- df4.melt2[,c("x","site","modification","rank")]
df7$group <- paste(df7$site,df7$modification,sep="_")
distfactor <- round(((max(df6$x2)+0)/max(df7$rank))*100)/100
df7 <- df7[order(df7$rank),]
y.tmp <- c(rbind(rep(maxy,ceiling(dim(df7)[1]/2)),rep(maxy*3,ceiling(dim(df7)[1]/2))))
df7$newy <- y.tmp[1:dim(df7)[1]]
df7$newrank <-  seq((distfactor/2)-0,(max(df6$x2)),by=distfactor)[-splitrank2]
df8 <- df7[,c("newrank","site","modification","group","newy")]
df7$rank <- NULL
df7$newrank <- NULL
df7$y <- rep(miny,dim(df7)[1])
df8$y <- rep(maxy,dim(df8)[1])
colnames(df8) <- colnames(df7)
df7 <- rbind(df7,df8)
df7.upper <- df7[df7$y==maxy,]
df7.upper$y <- (df7.upper$y*2)+df7.upper$newy/2
df7.upper <- rbind(df7[df7$y==maxy,],df7.upper)
df7.lower <- df7[df7$y==miny,]
df7.lower$y <- df7.lower$y*2
df7.lower <- rbind(df7[df7$y==miny,],df7.lower)

dfC7 <- dfC4.melt2[,c("x","site","modification","rank")]
dfC7.tmp <- dfC4.melt2[,c("y","site","modification","rank")]
colnames(dfC7.tmp) <- colnames(dfC7)
dfC7 <- rbind(dfC7,dfC7.tmp)
dfC7$group2 <- paste(dfC7$site,dfC7$modification,dfC7$x,sep="_")
dfC7$group <- paste(dfC7$site,dfC7$modification,sep="_")
dfC7 <- dfC7[!duplicated(dfC7),]
dfC7 <- dfC7[order(dfC7$rank,dfC7$x),]
y.tmp <- c(rbind(rep(maxy,ceiling(dim(dfC7)[1]/2)),rep(maxy*3,ceiling(dim(dfC7)[1]/2))))
dfC7$newy <- y.tmp[1:dim(dfC7)[1]]
dfC7$y <- rep(miny,dim(dfC7)[1])
dfC7.lower <- dfC7
dfC7.lower$y <- dfC7.lower$y*2
dfC7.lower <- rbind(dfC7,dfC7.lower)

dfC7 <- dfC4.melt2[,c("x","site","modification","rank")]
dfC7$group2 <- paste(dfC7$site,dfC7$modification,dfC7$x,sep="_")
dfC7$group <- paste(dfC7$site,dfC7$modification,sep="_")
dfC7 <- dfC7[order(dfC7$rank,dfC7$x),]
distfactor <- round(((max(df6$x2)-2)/max(dfC7$rank))*100)/100
dfC7$newrank <-  seq((distfactor/2)+2,max(df6$x2),by=distfactor)[-splitrankC2]
dfC7 <- dfC7[,c("newrank","site","modification","group","group2")]
colnames(dfC7) <- c("x","site","modification","group","group2")
y.tmp <- c(rbind(rep(maxy,ceiling(dim(dfC7)[1]/2)),rep(maxy*3,ceiling(dim(dfC7)[1]/2))))
dfC7$newy <- y.tmp[1:dim(dfC7)[1]]
dfC7$y <- rep(maxy,dim(dfC7)[1])
dfC7.upper <- dfC7
dfC7.upper$y <- (dfC7.upper$y*2)+dfC7.upper$newy/2
dfC7.upper <- rbind(dfC7,dfC7.upper)


dfC7 <- dfC4.melt2[,c("x","site","modification","rank")]
dfC7$group2 <- paste(dfC7$site,dfC7$modification,dfC7$x,sep="_")
dfC7$group <- paste(dfC7$site,dfC7$modification,sep="_")
dfC7 <- dfC7[order(dfC7$rank,dfC7$x),]
distfactor <- round(((max(df6$x2)-2)/max(dfC7$rank))*100)/100
dfC7$newrank <-  seq((distfactor/2)+2,max(df6$x2),by=distfactor)[-splitrankC2]
dfC7 <- dfC7[,c("newrank","site","modification","group","group2")]
colnames(dfC7) <- c("x","site","modification","group","group2")
dfC7.x <- dfC4.melt2[,c("y","site","modification","rank")]
dfC7.x$group2 <- paste(dfC7.x$site,dfC7.x$modification,dfC7.x$y,sep="_")
dfC7.x$group <- paste(dfC7.x$site,dfC7.x$modification,sep="_")
dfC7.x <- dfC7.x[order(dfC7.x$rank,dfC7.x$y),]
distfactor <- round(((max(df6$x2)-2)/max(dfC7.x$rank))*100)/100
dfC7.x$newrank <-  seq((distfactor/2)+2,max(df6$x2),by=distfactor)[-splitrankC2]
dfC7.x <- dfC7.x[,c("newrank","site","modification","group","group2")]
colnames(dfC7.x) <- c("x","site","modification","group","group2")
y.tmp <- c(rbind(rep(maxy,ceiling(dim(dfC7)[1]/2)),rep(maxy*3,ceiling(dim(dfC7)[1]/2))))
dfC7$newy <- y.tmp[1:dim(dfC7)[1]]
dfC7$y <- rep(maxy,dim(dfC7)[1])
y.tmp <- c(rbind(rep(maxy,ceiling(dim(dfC7.x)[1]/2)),rep(maxy*3,ceiling(dim(dfC7.x)[1]/2))))
dfC7.x$newy <- y.tmp[1:dim(dfC7.x)[1]]
dfC7.x$y <- rep(maxy,dim(dfC7.x)[1])

dfC7 <- rbind(dfC7,dfC7.x)
dfC7.x <- dfC4.melt2[,c("x","site","modification","rank")]
dfC7.x$group2 <- paste(dfC7.x$site,dfC7.x$modification,dfC7.x$x,sep="_")
dfC7.x$group <- paste(dfC7.x$site,dfC7.x$modification,sep="_")
dfC7.x <- dfC7.x[order(dfC7.x$rank,dfC7.x$x),]
y.tmp <- c(rbind(rep(maxy,ceiling(dim(dfC7.x)[1]/2)),rep(maxy*3,ceiling(dim(dfC7.x)[1]/2))))
dfC7.x$newy <- y.tmp[1:dim(dfC7.x)[1]]
dfC7.x$y <- rep(miny,dim(dfC7.x)[1])
dfC7.x$rank <- NULL
dfC7 <- rbind(dfC7,dfC7.x)
dfC7.x <- dfC4.melt2[,c("y","site","modification","rank")]
colnames(dfC7.x) <- c("x","site","modification","rank")
dfC7.x$group2 <- paste(dfC7.x$site,dfC7.x$modification,dfC7.x$x,sep="_")
dfC7.x$group <- paste(dfC7.x$site,dfC7.x$modification,sep="_")
dfC7.x <- dfC7.x[order(dfC7.x$rank,dfC7.x$x),]
y.tmp <- c(rbind(rep(maxy,ceiling(dim(dfC7.x)[1]/2)),rep(maxy*3,ceiling(dim(dfC7.x)[1]/2))))
dfC7.x$newy <- y.tmp[1:dim(dfC7.x)[1]]
dfC7.x$y <- rep(miny,dim(dfC7.x)[1])
dfC7.x$rank <- NULL
dfC7 <- rbind(dfC7,dfC7.x)



lwd4 <- 0.5
df7$newy <- df7$newy + (maxy-miny) + max(df6$y2)
df7$y <- df7$y + (maxy-miny) + max(df6$y2)
df7.upper$newy <- df7.upper$newy + (maxy-miny) + max(df6$y2)
df7.upper$y <- df7.upper$y + (maxy-miny) + max(df6$y2)
df7.lower$newy <- df7.lower$newy + (maxy-miny) + max(df6$y2)
df7.lower$y <- df7.lower$y + (maxy-miny) + max(df6$y2)

dfC7$newy <- dfC7$newy + (maxy-miny) + max(df6$y2)
dfC7$y <- dfC7$y + (maxy-miny) + max(df6$y2)
dfC7.upper$newy <- dfC7.upper$newy + (maxy-miny) + max(df6$y2)
dfC7.upper$y <- dfC7.upper$y + (maxy-miny) + max(df6$y2)

dfC7.lower$newy <- dfC7.lower$newy + (maxy-miny) + max(df6$y2)
dfC7.lower$y <- dfC7.lower$y + (maxy-miny) + max(df6$y2)

dfC7$newy <- dfC7$newy * -1
dfC7$y <- dfC7$y * -1
dfC7.upper$newy <- dfC7.upper$newy * -1
dfC7.upper$y <- dfC7.upper$y * -1
dfC7.lower$newy <- dfC7.lower$newy * -1
dfC7.lower$y <- dfC7.lower$y * -1

dfC8 <- dfC4.melt2[,c("site","modification","rank")]
dfC8$group <- paste(dfC8$site,dfC8$modification,sep="_")
dfC8$x1 <- rep(0,dim(dfC8)[1])
dfC8$x2 <- rep(0,dim(dfC8)[1])
dfC8$y1 <- rep(0,dim(dfC8)[1])
dfC8$y2 <- rep(0,dim(dfC8)[1])

dfC9 <- dfC7
dfC9$group2 <- NULL
dfC9 <- dfC9[!duplicated(dfC9),]


for(k in 1:dim(dfC8)[1]) {
  selected <- dfC8$group[k]
  tmp <- dfC7.lower[dfC7.lower$group==selected,]
  dfC8[dfC8$group==selected,]$x1 <- min(tmp$x)
  dfC8[dfC8$group==selected,]$x2 <- max(tmp$x)
  dfC8[dfC8$group==selected,]$y1 <- min(tmp$y)
  dfC8[dfC8$group==selected,]$y2 <- max(tmp$y)
}

dfC7.upper$site <- unlist(lapply(dfC7.upper$site,function(x){xx <- unlist(strsplit(x,"-")); y <- x; if(xx[1]==xx[2]){ y <- xx[1] }; y}))


df7.upper[df7.upper$y==0.65,]$y <- 0.8
df7.upper$textcolor <- rep("light",dim(df7.upper)[1])
df7.upper[df7.upper$modification%in%c("GG","Methyl"),]$textcolor <- "dark"

dfC7.upper[dfC7.upper$site%in%c("7-13","103-115","227-229","244-247","279-280","296-298","300-312","323-332","355-361","385","408-409"),]$modification <- "C-term"
dfC7.upper$textcolor <- rep("light",dim(dfC7.upper)[1])

topmargin <- 0.1
lwd4.1 <- 0.8
divideby <- 3
divideby2 <- 3
offset <- 12
g_connectionPTM <- ggplot() +
  geom_line(data=df7,aes(x=-x,y=-y,group=group,color=modification),lwd=lwd4.1) +
  geom_line(data=df7.upper,aes(x=-x,y=-y,group=group,color=modification),lwd=lwd4.1) +
  geom_line(data=df7.lower,aes(x=-x,y=-y,group=group),lwd=lwd4.1) +
  geom_rect(data=dfC8,mapping=aes(xmin=-x1,xmax=-x2,ymin=-y1,ymax=-y2,fill=modification,color=modification)) +
  geom_polygon(data=dfC9,mapping=aes(x=-x,y=-y,fill=modification,color=modification,group=group)) +
  geom_line(data=dfC7,aes(x=-x,y=-y,group=group2),color="black",lwd=lwd4.1) +
  geom_line(data=dfC7.upper,aes(x=-x,y=-y,group=group2),color="black",lwd=lwd4.1) +
  geom_line(data=dfC7.lower,aes(x=-x,y=-y,group=group2),color="black",lwd=lwd4.1) +
  geom_rect(data=df6,mapping=aes(xmin=-x1,xmax=-x2,ymin=-y1,ymax=-y2,fill=colo),color="black") +
  geom_text(data=df6,aes(x=-(x1+(x2-x1)/2),y=-(y1+(y2-y1)/2),label=name),size=textsize/divideby2,angle=270) +
  geom_label(data=subset(df7.upper,y>(maxy)+(maxy-miny)+max(df6$y2)),aes(x=-x,y=-(y+maxy/2),label=site,color=textcolor,fill=modification),size=textsize/divideby) +
  geom_label(data=subset(dfC7.upper,y<(miny)-(maxy-miny)-max(df6$y2)),aes(x=-x,y=-(y-maxy),label=site,color=textcolor,fill=modification),size=textsize/divideby) +
  geom_text(data=data.frame(x=c(-1-offset,-441+offset),y=c(0,0),term=c("N-term","C-term")),aes(x=x,y=y,label=term),size=textsize/divideby2,angle=270) +
  geom_text(data=data.frame(x=c(4),y=c(0),term=c("2N4R-Tau")),aes(x=x,y=y,label=term),size=textsize/divideby2) +
  geom_text(data=data.frame(x=c(12,12),y=c(-0.7,0.5),side=c("PTMs","Cleavages")),aes(x=x,y=y,label=side),size=textsize/2) +
  scale_x_continuous(expand=c(0.005,0.01),limits=c(-443,17)) +
  scale_y_continuous(expand=c(0.005,0.1),limits=c(NA,0.8)) +
  coord_flip() +
  scale_fill_manual(values=c(cleavage_col,col,c("B"="#E6E6E6","A"="#F9F9F9"))) + #c("B"="#677ABC","A"="#ACBBE2"))) + #scale_fill_manual(values=c("B"="#5599FF","A"="#AACCFF")) +
  scale_color_manual("Modification", values=c(cleavage_col,col,c("light"="#FFFFFF","dark"="#000000")), labels=c("N-term"="N-term Cleavage","C-term"="C-term cleavage","Acetyl"="Acetylation","Phospho"="Phosphorylation","GG"="Ubiquitination","Methyl"="Methylation")) +
  theme(legend.position="none",panel.grid=element_blank(),plot.margin=unit(c(topmargin-0.2,0.1,bottommargin,0.1),"line"),panel.background=element_blank(),axis.text=element_blank(),axis.ticks=element_blank(),axis.title=element_blank(),panel.spacing.y=unit(0,"lines"))


# defining the output of individual subplots in the overall plot composition
m0 <- 1
m1 <- 37
m2 <- 11
n1 <- 5
n0 <- 0
layout <- rbind(matrix(rep(rep(NA,m1),0),ncol=m1),
                matrix(rep(rep(1,m1),m2),ncol=m1),
                matrix(c(rep(NA,m0),rep(2,m1-m0)),ncol=m1),
                matrix(rep(rep(NA,m1),0),ncol=m1),
                matrix(c(rep(rep(3,m1),m2)),ncol=m1),
                matrix(rep(rep(4,m1),m2),ncol=m1))

layout.tmp <- rbind(matrix(c(rep(NA,n0),rep(5,n1*m2)),ncol=n1),
                    matrix(c(rep(NA,n0),rep(6,n1*m2)),ncol=n1),
                    matrix(c(rep(NA,n0),rep(NA,n1*m0)),ncol=n1),
                    matrix(c(rep(NA,n0),rep(7,n1*m2)),ncol=n1))
layout <- cbind(layout,layout.tmp)
layout <- t(layout)


p_total <- grid.arrange(grobs=list(g,p2,g_connectionPTM,g2,p_legend,p2_legend,p3_legend),layout_matrix=layout)

# PNG output
#p_total <- annotate_figure(p_total,top=text_grob("A                                                                                                            B                                                       ",face="bold",size=20))
#ggsave(fileout,p_total,device="png",width=17,height=20,units="cm",dpi=600,scale=2)

# PDF output
p_total <- annotate_figure(p_total,top=text_grob("A                                                                                                                                      B                                                                      ",face="bold",size=20))
ggsave(fileout,p_total,device="pdf",width=8.27,height=9.06,units="in",scale=2)
}
```

```{r,include=FALSE}
infile <- "PP_INSOL_reformat_combine.csv"
infileC <- "PP_INSOL_reformat_combine_C_collmean.csv"
fileout <- "Figure2.pdf"
createFigure(infile,infileC,fileout,0.00,10,0.01)
```
